version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Do nothing
          command: echo "This is a no-op."
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
